#!/bin/sh
#
# chkconfig: - 86 12
# description: Start/Stop the MikBiLL server daemon
#

# Source function library.
. /etc/rc.d/init.d/functions

prog="MikBiLL"
LOCKF=/var/lock/subsys/mikbill
RUN_SCRIPT=/usr/local/sbin/mikbill_run.sh
RAD_PID=/var/lock/subsys/radiusd
MIKBILL_PID=/var/run/mikbill.pid
RETVAL=0

start() {
        echo -n $"Starting $prog server: OK" 
        echo
        rm -rf $MIKBILL_PID
	if [ ! -f $LOCKF ] ; then
		daemon $RUN_SCRIPT & 2>/dev/null
	fi 
	RETVAL=$?
	touch $LOCKF 
	return 1
}
stop() {
	echo -n $"Stopping $prog server: OK"
	echo
	if [ -f $RAD_PID ] ; then
	    /etc/init.d/radiusd stop 2>/dev/null 2>&1
	    sleep 1
	fi
        kill -9 `ps auxfw|grep mikbill_run.sh|grep usr|awk {'print $2'}` 2>/dev/null 2>&1
        kill -9 `ps auxfw|grep mikbill.php|grep /usr/bin|awk {'print $2'}` 2>/dev/null 2>&1
	RETVAL=$?
	rm -f $LOCKF
	rm -rf $MIKBILL_PID
	return 1
}
status_check() {
	echo -n $"Status $prog server PID: "
	echo `ps auxfw|grep mikbill.php|awk {'print $2'}`
	status mikbill
	return 1
}
restart() {                                                                                                           
	echo -n $"Reloading $prog server: OK "
        stop
        sleep 1
        start
        return 1
}     
case "$1" in
  start)
	start
	status_check
	;;
  stop)
	stop
	status_check	
	;;
  status)
	status_check
        ;;
  reload)
	restart
	;;
  restart)
	restart
	;;
  condrestart)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
	status_check
	exit 1
esac
echo ""
exit
