From centos:6.8
RUN yum update -y && \
yum install -y  mysql-libs postgresql-libs unixODBC libpcap perl-DBI && \
yum clean all && \
rpm -ihv https://github.com/mikbill/distr/blob/master/rad_dhcp/radius_rpm/freeradius-2.2.6-1.el6.x86_64.rpm?raw=true && \
rpm -ihv https://github.com/mikbill/distr/blob/master/rad_dhcp/radius_rpm/freeradius-mysql-2.2.6-1.el6.x86_64.rpm?raw=true && \
rpm -ihv https://github.com/mikbill/distr/blob/master/rad_dhcp/radius_rpm/freeradius-perl-2.2.6-1.el6.x86_64.rpm?raw=true && \
rpm -ihv https://github.com/mikbill/distr/blob/master/rad_dhcp/radius_rpm/freeradius-utils-2.2.6-1.el6.x86_64.rpm?raw=true
EXPOSE 1812 1813 67 68

