From centos:6.8
RUN yum update -y && \
yum install -y wget && \
yum install mysql-libs -y && \
yum install postgresql-libs -y && \
yum install unixODBC -y && \
yum install libpcap -y && \
yum install perl-DBI -y && \
yum clean all && \
wget http://194.125.224.7/6/x86_64/freeradius-2.2.6-1.el6.x86_64.rpm && \
wget http://194.125.224.7/6/x86_64/freeradius-mysql-2.2.6-1.el6.x86_64.rpm && \
wget http://194.125.224.7/6/x86_64/freeradius-perl-2.2.6-1.el6.x86_64.rpm && \
wget http://194.125.224.7/6/x86_64/freeradius-utils-2.2.6-1.el6.x86_64.rpm && \
rpm -i freeradius-2.2.6-1.el6.x86_64.rpm && \
rpm -i freeradius-perl-2.2.6-1.el6.x86_64.rpm && \
rpm -i freeradius-mysql-2.2.6-1.el6.x86_64.rpm && \
rpm -i freeradius-utils-2.2.6-1.el6.x86_64.rpm
EXPOSE 1812 1813 67 68 2007

