SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
DROP DATABASE IF EXISTS `mikbill`;
CREATE DATABASE `mikbill` DEFAULT CHARACTER SET koi8r COLLATE koi8r_general_ci;
CREATE USER 'mikbill'@'localhost' IDENTIFIED BY 'MIKBILLPASS';
GRANT PROCESS , SUPER ON *.* TO 'mikbill'@'localhost' IDENTIFIED BY 'MIKBILLPASS' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
GRANT ALL PRIVILEGES ON `mikbill`.* TO 'mikbill'@'localhost' WITH GRANT OPTION ;
FLUSH PRIVILEGES;
SET FOREIGN_KEY_CHECKS=1;

